#!/bin/bash
CUR_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

PROD='yes'
VERSION='v1.0.10'
THEME='example'
DIR="${1:-}"

if [ "$DIR" == '' ]; then
    DIR="${CUR_DIR}/../lpmotor1/web/mottor-ui"
fi

echo "Build dir: $DIR"

UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_FONT_FAMILY='Noto Sans' UI_FONT_SIZE=14 ./gulp build
UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_CSS_NAME=mottorUI-cera-pro UI_FONT_FAMILY='Cera Pro' ./gulp build
UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_CSS_NAME=mottorUI-avenir-next-cyr UI_FONT_FAMILY='Avenir Next Cyr' ./gulp build
UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_CSS_NAME=mottorUI-tt-norms UI_FONT_FAMILY='TT Norms' ./gulp build
UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_CSS_NAME=mottorUI-tt-commons UI_FONT_FAMILY='TT Commons' ./gulp build

UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_CSS_NAME=mottorUI-ibm-plex-sans UI_FONT_FAMILY='IBM Plex Sans' ./gulp build
UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_CSS_NAME=mottorUI-noto-sans UI_FONT_FAMILY='Noto Sans' ./gulp build
UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_CSS_NAME=mottorUI-open-sans UI_FONT_FAMILY='Open Sans' ./gulp build
UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_CSS_NAME=mottorUI-proxima-nova-regular UI_FONT_FAMILY='Proxima Nova Rg' ./gulp build
UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_CSS_NAME=mottorUI-pt-sans UI_FONT_FAMILY='PT Sans' ./gulp build
UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_CSS_NAME=mottorUI-roboto UI_FONT_FAMILY='Roboto' ./gulp build
UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_CSS_NAME=mottorUI-graphik UI_FONT_FAMILY='Graphik' ./gulp build
UI_PROD=$PROD UI_VERSION=$VERSION UI_THEME=$THEME UI_BUILD_DIR=$DIR UI_CSS_NAME=mottorUI-museo-sans UI_FONT_FAMILY='Museo Sans' ./gulp build
